data:
 build: jenkins-data
 
master:
  build: jenkins-master
  volumes:
    - ./backup:/backup
  volumes_from:
    - data
  ports:
    - "${MASTER_PORT}:50000"
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
nginx:
  build: jenkins-nginx
  ports:
     - "${HTTP_PORT}:80" # Need to make this configurable, as we'll want 80:80 in 'prod' environments
  links:
     - master:jenkins-master
